const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.TextBox,
		C3.Plugins.Arr,
		C3.Plugins.Button,
		C3.Plugins.Multiplayer,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.LocalStorage,
		C3.Plugins.Json,
		C3.Plugins.XML,
		C3.Plugins.AJAX,
		C3.Plugins.NinePatch,
		C3.Plugins.Sprite,
		C3.Plugins.List,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.wrap,
		C3.Behaviors.Flash,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Multiplayer.Acts.AddClientInputValue,
		C3.Plugins.Multiplayer.Acts.SyncObject2,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Multiplayer.Cnds.OnSignallingDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnSignallingError,
		C3.Plugins.Multiplayer.Exps.ErrorMessage,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLeftRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingKicked,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.XML.Cnds.ForEach,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.XML.Exps.NodeCount,
		C3.Plugins.XML.Exps.NumberValue,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Json.Acts.SetBoolean,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Json.Acts.ToggleBoolean,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Tilemap.Acts.EraseTile,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Tilemap.Acts.SetTileWithBrush,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.MoveTo.Exps.MovingAngle,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Exps.time,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.Pathfinding.Acts.SetAcc,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Behaviors.Pathfinding.Acts.SetDec,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.getbit,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.AdvancedRandom.Exps.Ridged2d,
		C3.Plugins.AdvancedRandom.Exps.Cellular2d,
		C3.Plugins.AdvancedRandom.Exps.Classic2d,
		C3.Plugins.Tilemap.Acts.SetTileWithBrushByName,
		C3.Plugins.Tilemap.Acts.SetTileRange,
		C3.Plugins.Tilemap.Acts.EraseTileRange,
		C3.Plugins.Tilemap.Exps.MapDisplayWidth,
		C3.Plugins.Tilemap.Exps.MapDisplayHeight,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Tilemap.Acts.LoadFromJSON,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Multiplayer.Exps.PeerAliasFromID,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Tilemap.Exps.TilesJSON,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetBlur,
		C3.Plugins.Button.Acts.SetBlur,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Multiplayer.Acts.AssociateObjectWithPeer,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Exps.setbit,
		C3.Plugins.Multiplayer.Exps.PeerState,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Multiplayer.Cnds.OnHostDisconnected,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Multiplayer.Acts.InputPredictObject,
		C3.Plugins.Multiplayer.Cnds.OnClientUpdate,
		C3.Plugins.Multiplayer.Acts.SetClientState,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Spritefont2.Cnds.PickDistance,
		C3.Plugins.System.Exps.float,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Tilemap.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.Plugins.Multiplayer.Cnds.SignallingIsConnected,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.Multiplayer.Acts.SignallingRequestRoomList,
		C3.Plugins.AdvancedRandom.Acts.SetSeed,
		C3.Plugins.AdvancedRandom.Exps.RandomSeed,
		C3.Plugins.AdvancedRandom.Acts.SetOctaves,
		C3.Plugins.List.Cnds.IsVisible,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.Multiplayer.Cnds.OnRoomList,
		C3.Plugins.Multiplayer.Exps.ListRoomCount,
		C3.Plugins.Multiplayer.Exps.ListRoomName,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected
	];
};
self.C3_JsPropNameTable = [
	{Gamepad: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{chat: 0},
	{chatInputBox: 0},
	{ChatLog: 0},
	{sendChatButton: 0},
	{Multiplayer: 0},
	{Browser: 0},
	{Audio: 0},
	{AdvancedRandom: 0},
	{LocalStorage: 0},
	{SaveJSON: 0},
	{LevelJSON: 0},
	{InventoryJSON: 0},
	{RecipeXML: 0},
	{AJAX: 0},
	{menu_background: 0},
	{title: 0},
	{singleplayer_button: 0},
	{multiplayer_button: 0},
	{selectworldbox: 0},
	{selectworldlabel: 0},
	{play_button: 0},
	{worldnamebox: 0},
	{nameworldlabel: 0},
	{usernamebox: 0},
	{usernamelabel: 0},
	{ok_button: 0},
	{welcomelabel: 0},
	{delete_button: 0},
	{joinworldbox: 0},
	{back_button: 0},
	{join_button: 0},
	{loading_overlay: 0},
	{itemCount: 0},
	{generation_text: 0},
	{worldtypebox: 0},
	{worldsizebox: 0},
	{worldsizelabel: 0},
	{worldtypelabel: 0},
	{drops: 0},
	{hp: 0},
	{maxHP: 0},
	{contactDamage: 0},
	{axePower: 0},
	{pickPower: 0},
	{hard: 0},
	{defense: 0},
	{OakTree: 0},
	{CactusO: 0},
	{SpruceTree: 0},
	{smash: 0},
	{ai: 0},
	{speed: 0},
	{range: 0},
	{direction: 0},
	{themeMusic: 0},
	{boss: 0},
	{movingAngle: 0},
	{moving: 0},
	{attackPattern: 0},
	{Zombie: 0},
	{SlimeE: 0},
	{Rock: 0},
	{FloweringCactus: 0},
	{IronOreRock: 0},
	{WorkbenchO: 0},
	{FurnaceO: 0},
	{AnvilO: 0},
	{mob: 0},
	{spawnDelay: 0},
	{remainingDelay: 0},
	{Spawner: 0},
	{Dark_WorkbenchO: 0},
	{SlimeiumOreRock: 0},
	{SlimeKing: 0},
	{UpStairs: 0},
	{DownStairs: 0},
	{EnchantedZombie: 0},
	{RockwoodTree: 0},
	{canPickUp: 0},
	{heal: 0},
	{useSound: 0},
	{useAction: 0},
	{swordPower: 0},
	{energyCost: 0},
	{consumable: 0},
	{Wood: 0},
	{Cactus: 0},
	{Apple: 0},
	{Acorn: 0},
	{Plank: 0},
	{Wooden_Pickaxe: 0},
	{Wooden_Axe: 0},
	{CactuBread: 0},
	{Stone: 0},
	{Stone_Pickaxe: 0},
	{Stone_Axe: 0},
	{Cactus_Flower: 0},
	{Cactus_Pod: 0},
	{Floral_CactuBread: 0},
	{Workbench: 0},
	{Iron_Ore: 0},
	{Iron_Ingot: 0},
	{Furnace: 0},
	{Iron_Pickaxe: 0},
	{Iron_Axe: 0},
	{Anvil: 0},
	{Slimeium_Ore: 0},
	{Slimeium_Ingot: 0},
	{Slime: 0},
	{Slimeium_Pickaxe: 0},
	{Slimeium_Axe: 0},
	{Iron_Acorn: 0},
	{Slime_Spawner: 0},
	{Rotten_Flesh: 0},
	{Dark_Workbench: 0},
	{Dark_Cactus_Flower: 0},
	{Slimeium_Acorn: 0},
	{Wooden_Sword: 0},
	{Stone_Sword: 0},
	{Iron_Sword: 0},
	{Slimeium_Sword: 0},
	{Slime_Crown: 0},
	{Magic_Staff: 0},
	{Mana_Crystal: 0},
	{Enchanted_Zombie_Spawner: 0},
	{Azure_Essence: 0},
	{Spectral_Axe: 0},
	{Spectral_Pickaxe: 0},
	{heartContainer: 0},
	{hearts: 0},
	{mode: 0},
	{menu: 0},
	{menu_text: 0},
	{energyContainer: 0},
	{energy: 0},
	{spentEnergyContainer: 0},
	{held_item: 0},
	{ingredients_menu: 0},
	{ingredients_text: 0},
	{bossHeartContainer: 0},
	{bossHearts: 0},
	{bossLabel: 0},
	{dark_overlay: 0},
	{darkness: 0},
	{pierce: 0},
	{remainingPierces: 0},
	{hitSound: 0},
	{hitEffect: 0},
	{owner: 0},
	{friendly: 0},
	{MagicBolt: 0},
	{SlimeGlob: 0},
	{AxeProjectile: 0},
	{PickaxeProjectile: 0},
	{inputs: 0},
	{maxEnergy: 0},
	{damage: 0},
	{inventory: 0},
	{heldItem: 0},
	{stairCooldown: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{Wrap: 0},
	{Flash: 0},
	{player: 0},
	{Tilemap: 0},
	{Solid: 0},
	{SolidTilemap: 0},
	{DetailTilemap: 0},
	{DirtFloor: 0},
	{playerUID: 0},
	{hit: 0},
	{resourceUID: 0},
	{Pin: 0},
	{slash: 0},
	{Tween: 0},
	{text_particle: 0},
	{Dust: 0},
	{Buttons: 0},
	{Sine: 0},
	{Objects: 0},
	{Resources: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{Pathfinding: 0},
	{BoundToLayout: 0},
	{Entities: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Projectiles: 0},
	{Singleplayer: 0},
	{Username: 0},
	{DQ: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{Chatting: 0},
	{LevelData: 0},
	{CreateNewWorld: 0},
	{WorldName: 0},
	{WorldType: 0},
	{WorldSize: 0},
	{CurrentHeight: 0},
	{CurrentTemperature: 0},
	{InventoryOffset: 0},
	{RecipeOffset: 0},
	{SelectedInventoryItem: 0},
	{SelectedRecipe: 0},
	{SelectedRecipeName: 0},
	{ReadyToSave: 0},
	{Exhausted: 0},
	{JustAttacked: 0},
	{SelectedItemName: 0},
	{SelectedItemDisplayName: 0},
	{GenerationMessage: 0},
	{SelectedRecipeCategory: 0},
	{DayLength: 0},
	{message: 0},
	{color: 0},
	{alias: 0},
	{testx: 0},
	{testy: 0},
	{tries: 0},
	{projectileUID: 0},
	{projectileName: 0},
	{x: 0},
	{y: 0},
	{rotation: 0},
	{prevHP: 0},
	{objectToPlace: 0},
	{i: 0},
	{positive: 0},
	{moveLeft: 0},
	{canCraft: 0},
	{recipe: 0},
	{set: 0},
	{newInventoryItem: 0},
	{newOffset: 0},
	{favNav: 0},
	{force: 0},
	{item: 0},
	{count: 0},
	{displayName: 0},
	{ypos: 0},
	{xpos: 0},
	{resource: 0},
	{totalWeight: 0},
	{chance: 0},
	{mincount: 0},
	{maxcount: 0},
	{dropToSpawn: 0},
	{objectUID: 0},
	{amount: 0},
	{pink: 0},
	{hasPickPower: 0},
	{hasAxePower: 0},
	{willHit: 0},
	{spawnx: 0},
	{spawny: 0},
	{darkLevel: 0},
	{tile: 0},
	{temperature: 0},
	{object: 0},
	{value: 0},
	{oppositeValue: 0},
	{solid: 0},
	{overrideSolid: 0},
	{height: 0},
	{identifier: 0},
	{SelectedObjectId: 0},
	{Worlds: 0},
	{loadWorld: 0}
];

self.InstanceType = {
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	chat: class extends self.ISpriteFontInstance {},
	chatInputBox: class extends self.ITextInputInstance {},
	ChatLog: class extends self.IArrayInstance {},
	sendChatButton: class extends self.IButtonInstance {},
	Multiplayer: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	SaveJSON: class extends self.IJSONInstance {},
	LevelJSON: class extends self.IJSONInstance {},
	InventoryJSON: class extends self.IJSONInstance {},
	RecipeXML: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	menu_background: class extends self.IWorldInstance {},
	title: class extends self.ISpriteInstance {},
	singleplayer_button: class extends self.ISpriteInstance {},
	multiplayer_button: class extends self.ISpriteInstance {},
	selectworldbox: class extends self.IListInstance {},
	selectworldlabel: class extends self.ISpriteFontInstance {},
	play_button: class extends self.ISpriteInstance {},
	worldnamebox: class extends self.ITextInputInstance {},
	nameworldlabel: class extends self.ISpriteFontInstance {},
	usernamebox: class extends self.ITextInputInstance {},
	usernamelabel: class extends self.ISpriteFontInstance {},
	ok_button: class extends self.ISpriteInstance {},
	welcomelabel: class extends self.ISpriteFontInstance {},
	delete_button: class extends self.ISpriteInstance {},
	joinworldbox: class extends self.IListInstance {},
	back_button: class extends self.ISpriteInstance {},
	join_button: class extends self.ISpriteInstance {},
	loading_overlay: class extends self.ISpriteInstance {},
	generation_text: class extends self.ISpriteFontInstance {},
	worldtypebox: class extends self.IListInstance {},
	worldsizebox: class extends self.IListInstance {},
	worldsizelabel: class extends self.ISpriteFontInstance {},
	worldtypelabel: class extends self.ISpriteFontInstance {},
	OakTree: class extends self.ISpriteInstance {},
	CactusO: class extends self.ISpriteInstance {},
	SpruceTree: class extends self.ISpriteInstance {},
	smash: class extends self.ISpriteInstance {},
	Zombie: class extends self.ISpriteInstance {},
	SlimeE: class extends self.ISpriteInstance {},
	Rock: class extends self.ISpriteInstance {},
	FloweringCactus: class extends self.ISpriteInstance {},
	IronOreRock: class extends self.ISpriteInstance {},
	WorkbenchO: class extends self.ISpriteInstance {},
	FurnaceO: class extends self.ISpriteInstance {},
	AnvilO: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Dark_WorkbenchO: class extends self.ISpriteInstance {},
	SlimeiumOreRock: class extends self.ISpriteInstance {},
	SlimeKing: class extends self.ISpriteInstance {},
	UpStairs: class extends self.ISpriteInstance {},
	DownStairs: class extends self.ISpriteInstance {},
	EnchantedZombie: class extends self.ISpriteInstance {},
	RockwoodTree: class extends self.ISpriteInstance {},
	Wood: class extends self.ISpriteInstance {},
	Cactus: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	Acorn: class extends self.ISpriteInstance {},
	Plank: class extends self.ISpriteInstance {},
	Wooden_Pickaxe: class extends self.ISpriteInstance {},
	Wooden_Axe: class extends self.ISpriteInstance {},
	CactuBread: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	Stone_Pickaxe: class extends self.ISpriteInstance {},
	Stone_Axe: class extends self.ISpriteInstance {},
	Cactus_Flower: class extends self.ISpriteInstance {},
	Cactus_Pod: class extends self.ISpriteInstance {},
	Floral_CactuBread: class extends self.ISpriteInstance {},
	Workbench: class extends self.ISpriteInstance {},
	Iron_Ore: class extends self.ISpriteInstance {},
	Iron_Ingot: class extends self.ISpriteInstance {},
	Furnace: class extends self.ISpriteInstance {},
	Iron_Pickaxe: class extends self.ISpriteInstance {},
	Iron_Axe: class extends self.ISpriteInstance {},
	Anvil: class extends self.ISpriteInstance {},
	Slimeium_Ore: class extends self.ISpriteInstance {},
	Slimeium_Ingot: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Slimeium_Pickaxe: class extends self.ISpriteInstance {},
	Slimeium_Axe: class extends self.ISpriteInstance {},
	Iron_Acorn: class extends self.ISpriteInstance {},
	Slime_Spawner: class extends self.ISpriteInstance {},
	Rotten_Flesh: class extends self.ISpriteInstance {},
	Dark_Workbench: class extends self.ISpriteInstance {},
	Dark_Cactus_Flower: class extends self.ISpriteInstance {},
	Slimeium_Acorn: class extends self.ISpriteInstance {},
	Wooden_Sword: class extends self.ISpriteInstance {},
	Stone_Sword: class extends self.ISpriteInstance {},
	Iron_Sword: class extends self.ISpriteInstance {},
	Slimeium_Sword: class extends self.ISpriteInstance {},
	Slime_Crown: class extends self.ISpriteInstance {},
	Magic_Staff: class extends self.ISpriteInstance {},
	Mana_Crystal: class extends self.ISpriteInstance {},
	Enchanted_Zombie_Spawner: class extends self.ISpriteInstance {},
	Azure_Essence: class extends self.ISpriteInstance {},
	Spectral_Axe: class extends self.ISpriteInstance {},
	Spectral_Pickaxe: class extends self.ISpriteInstance {},
	heartContainer: class extends self.ITiledBackgroundInstance {},
	hearts: class extends self.ITiledBackgroundInstance {},
	menu: class extends self.IWorldInstance {},
	menu_text: class extends self.ISpriteFontInstance {},
	energyContainer: class extends self.ITiledBackgroundInstance {},
	energy: class extends self.ITiledBackgroundInstance {},
	spentEnergyContainer: class extends self.ITiledBackgroundInstance {},
	held_item: class extends self.ISpriteFontInstance {},
	ingredients_menu: class extends self.IWorldInstance {},
	ingredients_text: class extends self.ISpriteFontInstance {},
	bossHeartContainer: class extends self.ITiledBackgroundInstance {},
	bossHearts: class extends self.ITiledBackgroundInstance {},
	bossLabel: class extends self.ISpriteFontInstance {},
	dark_overlay: class extends self.ISpriteInstance {},
	darkness: class extends self.ISpriteInstance {},
	MagicBolt: class extends self.ISpriteInstance {},
	SlimeGlob: class extends self.ISpriteInstance {},
	AxeProjectile: class extends self.ISpriteInstance {},
	PickaxeProjectile: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	SolidTilemap: class extends self.ITilemapInstance {},
	DetailTilemap: class extends self.ITilemapInstance {},
	DirtFloor: class extends self.ITiledBackgroundInstance {},
	slash: class extends self.ISpriteInstance {},
	text_particle: class extends self.ISpriteFontInstance {},
	Dust: class extends self.IParticlesInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Objects: class extends self.ISpriteInstance {},
	Resources: class extends self.ISpriteInstance {},
	Entities: class extends self.ISpriteInstance {},
	Projectiles: class extends self.ISpriteInstance {}
}